config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :rulebooks
  devise_for :users, :controllers => { registrations: 'registrations' }

  # devise might handle all we need here
  resources :users, only: [:show, :index, :edit, :update]
  
  authenticated :user do
    root 'rulebooks#current'
  end
  
  root 'welcome#index'

  get 'homepage', to: 'welcome#index'

  get 'rulebook', to: 'rulebooks#current'
end

app/models/rulebook.rb
class Rulebook < ApplicationRecord
end

app/controllers/rulebook_controller.rb
class RulebookController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/rulebooks_controller.rb
class RulebooksController < ApplicationController
  before_action :set_rulebook, only: [:show, :update, :destroy]
  before_action :authenticate_user!, except: [:current]
  before_action :authenticate_user_is_admin!, only: [:index, :edit, :update, :destroy]

  # GET /rulebooks
  # GET /rulebooks.json
  def index
    @rulebooks = Rulebook.all.order(id: :desc)
  end

  # GET /rulebooks/1
  # GET /rulebooks/1.json
  def show
    @markdown_text = Markdown.new(@rulebook.markdown_text).to_html
  end

  def current
    @rulebook = Rulebook.last
    if @rulebook
      @markdown_text = Markdown.new(@rulebook.markdown_text).to_html
    else
      @rulebook = Rulebook.new
      @markdown_text = "<p>There was a problem fetching the latest rulebook</p>"
    end
      render "show"
  end

  # GET /rulebooks/new
  def new
    @rulebook = Rulebook.new
  end

  # GET /rulebooks/1/edit
  def edit
    @rulebook = Rulebook.find(params[:id])
  end

  # POST /rulebooks
  # POST /rulebooks.json
  def create
    @rulebook = Rulebook.new(rulebook_params)

    respond_to do |format|
      if @rulebook.save
        format.html { redirect_to @rulebook, notice: 'Rulebook was successfully created.' }
        format.json { render :show, status: :created, location: @rulebook }
      else
        format.html { render :new }
        format.json { render json: @rulebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rulebooks/1
  # PATCH/PUT /rulebooks/1.json
  def update
    respond_to do |format|
      if params[:id].to_i == Rulebook.last.try(:id)
        @rulebook = Rulebook.new
      end
      if @rulebook.update(rulebook_params.except(:id))
        format.html { redirect_to @rulebook, notice: 'Rulebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @rulebook }
      else
        format.html { render :edit }
        format.json { render json: @rulebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rulebooks/1
  # DELETE /rulebooks/1.json
  def destroy
    @rulebook.destroy
    respond_to do |format|
      format.html { redirect_to rulebooks_url, notice: 'Rulebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rulebook
      @rulebook = Rulebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rulebook_params
      params.require(:rulebook).permit(:major_version, :minor_version, :markdown_text)
    end
end

app/helpers/rulebook_helper.rb
module RulebookHelper
end

app/helpers/rulebooks_helper.rb
module RulebooksHelper
end

app/views/rulebooks/_form.html.erb
<%= stylesheet_link_tag "gollum_editor/gollum" %>
<%= javascript_include_tag "gollum_editor/gollum" %>

<%= form_for(rulebook) do |f| %>
  <% if rulebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rulebook.errors.count, "error") %> prohibited this rulebook from being saved:</h2>

      <ul>
      <% rulebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.gollum_editor :markdown_text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rulebooks/edit.html.erb
<h1 class="page-header">Editing Rulebook</h1>

<p>This page is written in markdown, checkout the documentation <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">here</a></p>

<%= render 'form', rulebook: @rulebook %>

<%= link_to 'Show', @rulebook %> |
<%= link_to 'Back', rulebooks_path %>

app/views/rulebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rulebooks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Version</th>
      <th>Character Count</th>
      <th>Last Updated At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rulebooks.each do |rulebook| %>
      <tr>
        <td><%= rulebook.id %></td>
        <td><%= rulebook.markdown_text.length %></td>
        <td><%= rulebook.updated_at.strftime("%F") %></td>
        <td><%= link_to 'Show', rulebook %></td>
        <td><%= link_to 'Edit', edit_rulebook_path(rulebook) %></td>
        <td><%= link_to 'Destroy', rulebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rulebook', new_rulebook_path %>

app/views/rulebooks/new.html.erb
<h1>New Rulebook</h1>

<%= render 'form', rulebook: @rulebook %>

<%= link_to 'Back', rulebooks_path %>

app/views/rulebooks/show.html.erb
<h1 class="page-header">
  Rulebook
  <% if user_signed_in? %>
    <a class="btn btn-default pull-right" href="<%= edit_rulebook_path(@rulebook) %>">Edit</a>
  <% end %>
</h1>
<%== @markdown_text %>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_rulebook_path(@rulebook) %>
<% end %>