config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :rulebooks
  devise_for :users, :controllers => { registrations: 'registrations' }

  # devise might handle all we need here
  resources :users, only: [:show, :index, :edit, :update]
  
  authenticated :user do
    root 'rulebooks#current'
  end
  
  root 'welcome#index'

  get 'homepage', to: 'welcome#index'

  get 'rulebook', to: 'rulebooks#current'
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:job_text, :job_subtext, :sorting_text, :sorting_subtext)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :job_text, "Job Text" %>
    <i class="helper-text">(how this card distributes monies)</i>
    <%= f.text_area :job_text, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :job_subtext, "Job Subtext" %>
    <i class="helper-text">(information for the dealer that they do not read out loud)</i>
    <%= f.text_area :job_subtext, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :sorting_text, "Sorting Text" %>
    <i class="helper-text">(true or false type question that determines who gets to bid on the card)</i>
    <%= f.text_area :sorting_text, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :sorting_subtext, "Sorting Subtext" %>
    <i class="helper-text">(information for the dealer that they do not read out loud)</i>
    <%= f.text_area :sorting_subtext, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Job Text</th>
      <th>Sorting Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.id %></td>
        <td><%= card.job_text %></td>
        <td><%= card.sorting_text %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>