config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :rulebooks
  devise_for :users, :controllers => { registrations: 'registrations' }

  # devise might handle all we need here
  resources :users, only: [:show, :index, :edit, :update]
  
  authenticated :user do
    root 'rulebooks#current'
  end
  
  root 'welcome#index'

  get 'homepage', to: 'welcome#index'

  get 'rulebook', to: 'rulebooks#current'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adulting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-md navbar-light">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Adulting</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to('Homepage', homepage_path, class: "nav-link") %>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/rulebook">Rulebook</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="/cards">Cards</a>
          </li>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to('Login', new_user_session_path, class: "nav-link") %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>